name: fishstick_dart
description: A multipurpose fortnite bot coded in dart.
version: 0.4.0

environment:
    sdk: ">=2.15.0 <3.0.0"

dependencies:
    # logging
    logging: ^1.0.2
    # libraries for database
    mongo_dart: ^0.7.4
    # libraries for discord api
    nyxx: ^3.2.2
    nyxx_interactions: ^3.1.0
    nyxx_commands: ^3.1.1
    nyxx_extensions: ^3.0.0
    nyxx_pagination: ^2.1.0
    # libraries for fortnite
    fortnite: ^1.1.51
    # utils
    async: ^2.8.2
    numeral: ^1.2.5
    time_ago_provider: ^4.1.2
    # encryption
    encrypt: ^5.0.1
    # get package info
    pubspec_yaml: ^3.1.0
    # http server
    shelf: ^1.2.0
    shelf_router: ^1.1.2
    shelf_letsencrypt: ^1.0.0

dev_dependencies:
    lints: ^1.0.0
