name: fishstick_dart
description: A multipurpose fortnite bot coded in dart.
version: 1.0.0

environment:
    sdk: ">=2.15.0 <3.0.0"

dependencies:
    #   path: ^1.8.0
    nyxx: any # discord library

dev_dependencies:
    lints: ^1.0.0
