name: fishstick_dart
description: A multipurpose fortnite bot coded in dart.
version: 0.0.0

environment:
    sdk: ">=2.15.0 <3.0.0"

dependencies:
    # libraries for database
    mongo_dart: ^0.7.4
    # libraries for discord api
    nyxx: ^3.2.1
    nyxx_interactions: ^3.1.0
    nyxx_commands: ^3.1.0
    nyxx_extensions: ^3.0.0
    nyxx_pagination: ^2.0.0
    # libraries for fortnite
    fortnite: ^1.1.2

dev_dependencies:
    lints: ^1.0.0
