name: fishstick_dart
description: A multipurpose fortnite bot coded in dart.
version: 1.0.0

environment:
    sdk: ">=2.16.0 <3.0.0"

dependency_overrides:
    nyxx_commands:
        git:
            url: https://github.com/nyxx-discord/nyxx_commands.git
            ref: feat/compile
            # url: https://github.com/vanxh/nyxx_commands/
            # ref: patch-3
    nyxx_pagination:
        git:
            url: https://github.com/vanxh/nyxx_pagination.git
            ref: patch-1

dependencies:
    # logging
    logging: ^1.0.2
    # libraries for database
    mongo_dart: ^0.7.4
    # libraries for discord api
    nyxx: ^3.3.0-dev.0
    nyxx_interactions: ^4.0.0-dev.0.1
    nyxx_commands: ^4.0.0-dev.1.2
    # nyxx_extensions: ^3.0.0
    # nyxx_pagination: ^2.1.0
    nyxx_sharding: ^1.0.0
    # libraries for telegram api
    teledart: ^0.3.2
    # libraries for fortnite
    fortnite: ^1.2.0
    # utils
    async: ^2.8.2
    time_ago_provider: ^4.1.2
    # parse numerals
    numeral: ^1.2.5
    # encryption
    encrypt: ^5.0.1
    # get package info
    pubspec_yaml: ^3.1.0
    # http
    dio: any
    # http server
    # shelf: ^1.2.0
    # shelf_router: ^1.1.2
    # image
    # image: ^3.1.1
    # image_extensions: ^0.2.0
    # cron
    cron: ^0.4.0

dev_dependencies:
    lints: ^1.0.0
    dependency_validator: ^3.0.0
