name: fishstick_dart
description: A multipurpose fortnite bot coded in dart.
version: 1.3.0

environment:
    sdk: ">=2.16.0 <3.0.0"

dependency_overrides:
    nyxx_commands:
        git:
            url: https://github.com/nyxx-discord/nyxx_commands.git
            ref: feat/compile
            # url: https://github.com/vanxh/nyxx_commands/
            # ref: patch-3

dependencies:
    logging: ^1.0.2 # for logging.
    mongo_dart: ^0.7.4 # to interact with mongo db database for bot.
    nyxx: ^3.3.0-dev.0 # to interact with discord api.
    nyxx_interactions: ^4.0.0-dev.0.1 # for handling interactions of discord bot.
    nyxx_commands: ^4.0.0-dev.1.2 # a discord bot commands handler.
    nyxx_pagination: ^2.2.0-dev.0 # for pagination support in discord bot.
    nyxx_sharding: ^2.0.0-dev.0.2 # for discord bot sharding.
    teledart: ^0.3.2 # to interact with telegram api.
    fortnite: ^1.3.21 # to interact with fortnite api.
    async: ^2.8.2 # uhmmm.
    time_ago_provider: ^4.1.2 # just for normal utility ig.
    numeral: ^1.2.5 # to parse numerals.
    encrypt: ^5.0.1 # for encryption of strings.
    pubspec_yaml: ^3.1.0 # to get package info.
    http: ^0.13.4 # for making http requests.
    dio: ^4.0.4 # for making http requests.
    cron: ^0.4.0 # cron for system jobs scheduling.

dev_dependencies:
    lints: ^1.0.0
    dependency_validator: ^3.0.0
