theme: jekyll-theme-hacker

author: Vanxh
title: Fishstick Bot
name: Fishstick Bot

tagline: A multipurpose fortnite bot that makes your life easy.
description: A multipurpose fortnite bot that makes your life easy.

url: https://docs.fishstickbot.com

permalink: /404.html

tags:
    - Fishstick
    - Fishstick Bot
    - Fortnite
    - STW
    - Fortnite STW
    - Skin Checker
    - Discord Bot
    - Locker image

links:
    - title: Home
      url: /
    - title: Discord
      url: https://discord.gg/fishstick

logo: "assets/fishstick.jpg"
avatar: "/assets/fishstick.jpg"
round-avatar: true

twitter_username: Vanxhh
github_username: vanxh
social-network-links:
    email: "vanxh@fishstickbot.com"
    rss: true
    github: vanxh
    twitter: Vanxhh
    instagram: vanxh.69
    discord: invite/fishstick
    linkedin: Vanxhh

url-pretty: "Docs.FishstickBot.com"

sitemap: true
